services:
  broker:
    image: redis:6.0
    restart: unless-stopped
    volumes:
      - redisdata:/data
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`paperless.app.danielr1996.de`)"
      - "traefik.http.routers.paperless.tls.certresolver=letsencrypt"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
  gotenberg:
    image: gotenberg/gotenberg:7.4
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.5,nolock,soft,rw"
      device: ":/mnt/user/compose-data/paperless/data"
  media:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.5,nolock,soft,rw"
      device: ":/mnt/user/compose-data/paperless/media"
  pgdata:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.5,nolock,soft,rw"
      device: ":/mnt/user/compose-data/paperless/pgdata"
  redisdata:
